### ISSUE TITLE
Модель пользователя

### ISSUE THREAD

**Issue by ArtemHelloWorld** [neeearina/jobik_api#10]
Советую всегда когда джанго проект начинаешь менять модель юзера через настройки AUTH_USER_MODEL 
 https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#substituting-a-custom-user-model
https://github.com/neeearina/jobik_api/blob/d9733c4efdda50ac7d453eb306942a7ae2f36e77/jobik_api/users/models.py#L7

**Comment by neeearina** [comment]
было сложно, но я сделала
